CREATE SCHEMA IF NOT EXISTS public;

CREATE USER ddl WITH PASSWORD 'ddl';
CREATE USER dml WITH PASSWORD 'dml';

GRANT CREATE, CONNECT, TEMP ON DATABASE jso_reg_agent TO ddl;
GRANT USAGE, CREATE ON SCHEMA public TO ddl;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ddl;

GRANT CONNECT ON DATABASE jso_reg_agent TO dml;
GRANT USAGE ON SCHEMA public TO dml;
ALTER DEFAULT PRIVILEGES FOR ROLE ddl IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dml;
