server:
    port: 8080

spring:
    application:
        name: jso-reg-agent

    datasource:
        url: jdbc:postgresql://localhost:5432/jso_reg_agent
        driver-class-name: org.postgresql.Driver
        username: dml
        password: dml

    jpa:
        hibernate:
            ddl-auto: none

    liquibase:
        user: ddl
        password: ddl